<<<<<<< HEAD
baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
=======
baseURL = "https://deloittedigitaluk.github.io/xLab"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "learn"
publishDir = "docs"
>>>>>>> 3a1d88ba246ab445318fe172c30e9d18f8a60241
